#spring:
#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/financeiro}
#    username: ${DATABASE_USER:postgres}
#    password: ${DATABASE_PASSWORD:postgres}
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    generate-ddl: false
#security:
#  oauth2:
#    client:
#      scope: password
#      client-id: frontfront
#      client-secret: frontend
#
