spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financeiro
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true
security:
  oauth2:
    client:
      scope: password
      client-id: frontfront
