version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    - image: circleci/postgres:9.6.5-alpine-ram

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      DATABASE_URL: jdbc:postgresql://localhost:5432/thunderpets
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    steps:
    - checkout

    - run: sudo apt-get update
    - run: sudo apt-get install postgresql-client-9.6
    - run:
        command: |
          psql -h localhost -U postgres -c "CREATE DATABASE thunderpets;"

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run: gradle dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run: gradle test
